### ISSUE TITLE
updatable = false on an PK column breaks optimistic locking

### ISSUE THREAD

**Issue by pandacalculus** [datanucleus/datanucleus-api-jpa#101]
## Bug Report 

failing test case:
https://github.com/pandacalculus/test-jpa

summary:
adding `updatable = false` in a `@Column` annotation on a `@Id` (PK) field prevents its inclusion in the WHERE clause of update statements using optimistic locking. 

For the test case referenced above, the expected UPDATE on commit should be:
```
UPDATE ENTITY SET _VERSION=<2> WHERE ID='1' AND _VERSION=<1>
```
but actual generated UPDATE is:
```
UPDATE ENTITY SET _VERSION=<2> WHERE _VERSION=<1>
```

**Comment by andyjefferson** [comment]
Firstly, putting `updatable="false"` on an `@Id` field would be pointless since a PK field cannot be updated in a datastore ever. Secondly, this is fixed by https://github.com/datanucleus/datanucleus-rdbms/issues/251

**Comment by pandacalculus** [comment]
@andyjefferson thanks for the quick turn around! I agree that `updatable = false` on a PK field is superfluous, but that didn't stop one of our developers doing it ;-)
