### ISSUE TITLE
JPA native query fails if PK has a table alias

### ISSUE THREAD

**Issue by pandacalculus** [datanucleus/datanucleus-api-jpa#102]
## Bug Report

A native query where the PK is prefixed with a table alias fails with the error:
```
SQL query ("select e.id, e.value from entity e where e.id = ?")
 has been specified with a candidate class "mydomain.model.MyEntity" yet the id 
column ("ID") has not been selected. When you specify a candidate class you MUST
 select the id column(s).
```
This problem is *not* present in 5.1.0-release.
This problem *is* present in 5.1.1 and 5.1.5.

Failing testcase demonstrating the problem:
https://github.com/pandacalculus/test-jpa

**Comment by andyjefferson** [comment]
Can't see how this has any relevance to the datanucleus-api-jpa plugin (which simply handles the JPA API wrapper), whilst this relates explicitly to SQL (hence the RDBMS plugin). If this is a problem with the RDBMS plugin then raise it there.
