### ISSUE TITLE
JPAEntityManager.unwrap() leaves locked connections

### ISSUE THREAD

**Issue by veselov** [datanucleus/datanucleus-api-jpa#103]
Calling `JPAEntityManager.unwrap()` with `java.sql.Connection.class` leaves underlying data nucleus connection in the locked state. This is because in this code path, first a `NucleusConnection` object is acquired from the "store manager". This creates the connection object that locks the underlying managed connection until it (the created connection object) is closed.
However, after the `getNucleusConnection()` call, the returned object is tested for it being an instance of `java.sql.Connection`, and only if that's so, the underlying connection is returned.

The nucleus connection object is therefore effectively lost. It can not be reached by the caller, so the caller can not call `close()` on it to release the lock. Also, the `instanceof java.sql.Connection` doesn't seem to be meaningful, as the nucleus connection objects are never instances of `java.sql.Connection`, and such test shouldn't be a reason to retrieve underlying connection. I think the intent may have been to return `nconn` if it is a `java.sql.Connection`, or return the underlying native connection only if it itself is a `java.sql.Connection`, but in both cases, the problem of leaving `nconn` open, holding the managed connection lock is a problem, as it ends up causing "The Connection was acquired by the developer and must be closed before using the persistence API", when the entity manager is attempted to be operated upon later.

**Comment by andyjefferson** [comment]
No testcase provided, and the docs state very clearly how to obtain access to the connection to the underlying datastore, namely by obtaining a NucleusConnection, hence it is manageable by the JPA provider. 
http://www.datanucleus.org:15080/products/accessplatform_5_1/jpa/persistence.html#_user_connection
