### ISSUE TITLE
Static metamodel generator generates null for byte[] properties

### ISSUE THREAD

**Issue by Mobe91** [datanucleus/datanucleus-api-jpa#36]
The static metamodel generator of Datanucleus 5 generates null for byte[] properties.
Testcase:
https://github.com/Mobe91/test-jpa/tree/metamodel-bug

**Comment by andyjefferson** [comment]
Arises from JPA spec deficiency in not defining what should happen with array fields (whether basic or relation). Now simply uses SingularAttribute.
