### ISSUE TITLE
Support OPTIMISTIC_FORCE_INCREMENT and PESSIMISTIC_FORCE_INCREMENT

### ISSUE THREAD

**Issue by jamestyrrell** [datanucleus/datanucleus-api-jpa#49]
OPTIMISTIC_FORCE_INCREMENT doesn't work, please see test case attached which can be run with the following command.

```
mvn test
```

[datanucleus-test.zip](https://github.com/datanucleus/datanucleus-api-jpa/files/550619/datanucleus-test.zip)

**Comment by andyjefferson** [comment]
Using current datanucleus-core means this is supported

**Comment by jamestyrrell** [comment]
Yayyyyy, thanks @andyjefferson! Looking forward to trying it out!
