### ISSUE TITLE
PersistenceUnitUtil returns LongId instead of Long for getIdentifier when using entity with single @Id field

### ISSUE THREAD

**Issue by beikov** [datanucleus/datanucleus-api-jpa#77]
Imagine the following

```java
@Entity
class Person {
    @Id
    Long id;
}
```

When wanting to extract the identifier of that entity via `PersistenceUnitUtil.getIdentifier()`.

```java
Person p = ...;
Object id = entityManager.getEntityManagerFactory().getPersistenceUnitUtil().getIdentifier(p);
```

The resulting object is unexpectedly of the type `LongId` instead of `Long`.

**Comment by andyjefferson** [comment]
backported fix from master, returns field type when using single-field @Id, and IdClass type when not.
